
root: /

Home: /
Archives: /archives
About: /about

language: zh-CN

author: ''
description:

email: ''

favicon: /favicon.ico


# stylesheets loaded in the <head>
stylesheets:
- /css/hexo-theme-adoubi.css
